<?php

declare(strict_types=1);

use Api\App\Template\ParserInterface;
use Core\User\Entity\User;
use Core\User\Entity\UserResetPassword;

/** @var ParserInterface $this */
/** @var array $application */
/** @var User $user */
/** @var UserResetPassword $resetPassword */

$resetUrl = $this->absoluteUrl(
    $this->url('user::update-account-reset-password', ['hash' => $resetPassword->getHash()])
);
?>

<div>
    <p>Hi <?=$user->getIdentity()?>,</p>

    <p>
        Someone requested a password reset for this account.<br />
        If you did not make this request, just ignore this email; no changes have been made to your account yet.
    </p>

    <p>
        Otherwise, you can reset your password by sending a PATCH request to the below endpoint:<br />
        <?=$resetUrl?>
    </p>

    <p>
        Thanks,<br />
        The <?=$application['name'] ?? ''?> Team
    </p>
</div>
