<?php

declare(strict_types=1);

use Api\App\Template\ParserInterface;
use Core\User\Entity\User;

/** @var ParserInterface $this */
/** @var array $application */
/** @var User $user */
?>

<div>
    <p>Hi <?=$user->getIdentity()?>,</p>

    <p>
        You have successfully reset your <?=$application['name'] ?? ''?> password.<br />
        You can now access your account using your email (<?=$user->getDetail()->getEmail()?>) and the password you set.
    </p>

    <p>
        Thanks,<br />
        The <?=$application['name'] ?? ''?> Team
    </p>
</div>
